services:
  # Backend API
  - type: web
    name: legalmu-api
    runtime: node
    region: ohio
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: staging
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOKSECRET
        sync: false
      - key: STRIPE_SUCCESS_URL
        sync: false
      - key: STRIPE_CANCEL_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend
  - type: web
    name: legalmu-web
    runtime: node
    region: ohio
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
